### PR TITLE
Character a a time mode

### PR DESCRIPTION
**Pull request by dfedyk**
Hi Bruno 

Let me know if this pull request works.

### CODE REVIEW

**Comment by dfedyk** [comment]
Attempted to back out the one line change in interface.py

**Comment by dfedyk** [comment]
OK is this successful now?  
Not sure how you would do code coverage.  I was my intent originally that if you sent a full command just as with line at a time it would work but it would echo each character and terminate with \r\n.   (The code could be simplified to have all commands return \r\n if the tests were flexible in this aspect. I originally had it that way but the tests failed.  In other words as far as I could tell telnet line at a time treats \r\n the same as \n.  But character mode needs an explicit \r\n.  Line at a time must generate a \r for every line of output terminated with \n.

**Comment by brunorijsman** [comment]
I see the Travis build (which runs the unit tests and the system tests) pass now, so I merged your pull request.  As far as code coverage is concerned, you see the coverage percentage when you run the CI tests tools/pre-commit-tests.  You won't see the fancy codecov graphs, but you will see the raw percentages. The idea is that the code coverage should "go in the right direction", i.e. not decrease. Since you added new code which was only covered for 45% by the tests, the overall code coverage dropped by 3.62 percentage points.  The way to address this would have been to add new unit test cases.

**Comment by brunorijsman** [comment]
Oh, and I forgot: thanks again for the contribution! This will make using the CLI a lot less frustrating.

**Comment by dfedyk** [comment]
OK I will explore Unit tests at a later date.  I just have a few deadlines the next couple of weeks. 
 Thank you - I've learned a lot from this exercise - Pycharm, Git, and your code model for FSM and schemas etc.  I'm a big FSM fan.

**Pull request merged**
